@echo off
echo Starting Wastewater Treatment Plant Monitoring System...
echo.

set BASE_PATH=%~dp0..\..
set PYTHON_PATH=python
set MONITOR_PATH=%BASE_PATH%\src\monitoring\system_status.py

:: Check if Python is available
%PYTHON_PATH% --version >nul 2>&1
if %ERRORLEVEL% NEQ 0 (
    echo Python not found in PATH. Please install Python 3.8 or higher.
    exit /b 1
)

:: Check if the monitor script exists
if not exist "%MONITOR_PATH%" (
    echo.
    echo Monitor script not found at: %MONITOR_PATH%
    echo Creating monitoring script...
    
    mkdir "%BASE_PATH%\src\monitoring" 2>nul
    
    echo import time > "%MONITOR_PATH%"
    echo import socket >> "%MONITOR_PATH%"
    echo import json >> "%MONITOR_PATH%"
    echo import threading >> "%MONITOR_PATH%"
    echo import datetime >> "%MONITOR_PATH%"
    echo import os >> "%MONITOR_PATH%"
    echo import sys >> "%MONITOR_PATH%"
    echo import flask >> "%MONITOR_PATH%"
    echo from flask import Flask, render_template, jsonify, request >> "%MONITOR_PATH%"
    echo. >> "%MONITOR_PATH%"
    echo class WastewaterMonitoringSystem: >> "%MONITOR_PATH%"
    echo     def __init__(self): >> "%MONITOR_PATH%"
    echo         self.simulator_host = '127.0.0.1' >> "%MONITOR_PATH%"
    echo         self.simulator_port = 9000 >> "%MONITOR_PATH%"
    echo         self.web_host = '127.0.0.1' >> "%MONITOR_PATH%"
    echo         self.web_port = 8051 >> "%MONITOR_PATH%"
    echo         self.running = True >> "%MONITOR_PATH%"
    echo         self.system_data = {} >> "%MONITOR_PATH%"
    echo         self.last_update = None >> "%MONITOR_PATH%"
    echo         self.update_interval = 2  # seconds >> "%MONITOR_PATH%"
    echo. >> "%MONITOR_PATH%"
    echo         # Start data polling thread >> "%MONITOR_PATH%"
    echo         self.poll_thread = threading.Thread(target=self.poll_data) >> "%MONITOR_PATH%"
    echo         self.poll_thread.daemon = True >> "%MONITOR_PATH%"
    echo         self.poll_thread.start() >> "%MONITOR_PATH%"
    echo. >> "%MONITOR_PATH%"
    echo         # Create Flask app >> "%MONITOR_PATH%"
    echo         self.app = Flask(__name__) >> "%MONITOR_PATH%"
    echo         self.setup_routes() >> "%MONITOR_PATH%"
    echo. >> "%MONITOR_PATH%"
    echo         # Start web server >> "%MONITOR_PATH%"
    echo         print(f"Starting Wastewater Treatment Monitoring System") >> "%MONITOR_PATH%"
    echo         print(f"Web interface available at http://{self.web_host}:{self.web_port}") >> "%MONITOR_PATH%"
    echo         print("Press Ctrl+C to stop the monitoring system") >> "%MONITOR_PATH%"
    echo. >> "%MONITOR_PATH%"
    echo         try: >> "%MONITOR_PATH%"
    echo             self.app.run(host=self.web_host, port=self.web_port, debug=False, use_reloader=False) >> "%MONITOR_PATH%"
    echo         except KeyboardInterrupt: >> "%MONITOR_PATH%"
    echo             self.running = False >> "%MONITOR_PATH%"
    echo             print("\nMonitoring system shutting down...") >> "%MONITOR_PATH%"
    echo. >> "%MONITOR_PATH%"
    echo     def poll_data(self): >> "%MONITOR_PATH%"
    echo         """Poll data from the simulator""" >> "%MONITOR_PATH%"
    echo         while self.running: >> "%MONITOR_PATH%"
    echo             try: >> "%MONITOR_PATH%"
    echo                 with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s: >> "%MONITOR_PATH%"
    echo                     s.connect((self.simulator_host, self.simulator_port)) >> "%MONITOR_PATH%"
    echo                     s.send(json.dumps({'type': 'get_data'}).encode('utf-8')) >> "%MONITOR_PATH%"
    echo                     data = s.recv(4096) >> "%MONITOR_PATH%"
    echo                     if data: >> "%MONITOR_PATH%"
    echo                         self.system_data = json.loads(data.decode('utf-8')) >> "%MONITOR_PATH%"
    echo                         self.last_update = datetime.datetime.now() >> "%MONITOR_PATH%"
    echo                         print(f"Data updated: {self.last_update.strftime('%H:%M:%S')}") >> "%MONITOR_PATH%"
    echo             except Exception as e: >> "%MONITOR_PATH%"
    echo                 print(f"Error polling data: {e}") >> "%MONITOR_PATH%"
    echo. >> "%MONITOR_PATH%"
    echo             time.sleep(self.update_interval) >> "%MONITOR_PATH%"
    echo. >> "%MONITOR_PATH%"
    echo     def setup_routes(self): >> "%MONITOR_PATH%"
    echo         """Set up Flask routes""" >> "%MONITOR_PATH%"
    echo         @self.app.route('/') >> "%MONITOR_PATH%"
    echo         def home(): >> "%MONITOR_PATH%"
    echo             return render_template_string(HTML_TEMPLATE) >> "%MONITOR_PATH%"
    echo. >> "%MONITOR_PATH%"
    echo         @self.app.route('/api/data') >> "%MONITOR_PATH%"
    echo         def api_data(): >> "%MONITOR_PATH%"
    echo             if not self.system_data: >> "%MONITOR_PATH%"
    echo                 return jsonify({'error': 'No data available'}) >> "%MONITOR_PATH%"
    echo. >> "%MONITOR_PATH%"
    echo             return jsonify(self.system_data) >> "%MONITOR_PATH%"
    echo. >> "%MONITOR_PATH%"
    echo         @self.app.route('/api/control', methods=['POST']) >> "%MONITOR_PATH%"
    echo         def api_control(): >> "%MONITOR_PATH%"
    echo             try: >> "%MONITOR_PATH%"
    echo                 control_data = request.get_json() >> "%MONITOR_PATH%"
    echo                 with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s: >> "%MONITOR_PATH%"
    echo                     s.connect((self.simulator_host, self.simulator_port)) >> "%MONITOR_PATH%"
    echo                     s.send(json.dumps({'type': 'set_control', 'control': control_data}).encode('utf-8')) >> "%MONITOR_PATH%"
    echo                     data = s.recv(1024) >> "%MONITOR_PATH%"
    echo                     if data: >> "%MONITOR_PATH%"
    echo                         return jsonify(json.loads(data.decode('utf-8'))) >> "%MONITOR_PATH%"
    echo                     else: >> "%MONITOR_PATH%"
    echo                         return jsonify({'status': 'error', 'message': 'No response from simulator'}) >> "%MONITOR_PATH%"
    echo             except Exception as e: >> "%MONITOR_PATH%"
    echo                 return jsonify({'status': 'error', 'message': str(e)}) >> "%MONITOR_PATH%"
    echo. >> "%MONITOR_PATH%"
    echo # Basic HTML template for the monitoring interface >> "%MONITOR_PATH%"
    echo HTML_TEMPLATE = """<!DOCTYPE html> >> "%MONITOR_PATH%"
    echo <html> >> "%MONITOR_PATH%"
    echo <head> >> "%MONITOR_PATH%"
    echo     <title>Wastewater Treatment Monitoring System</title> >> "%MONITOR_PATH%"
    echo     <meta charset="UTF-8"> >> "%MONITOR_PATH%"
    echo     <meta name="viewport" content="width=device-width, initial-scale=1.0"> >> "%MONITOR_PATH%"
    echo     <style> >> "%MONITOR_PATH%"
    echo         body { font-family: Arial, sans-serif; margin: 0; padding: 20px; background-color: #f5f5f5; } >> "%MONITOR_PATH%"
    echo         .header { background-color: #2c3e50; color: white; padding: 15px; text-align: center; margin-bottom: 20px; } >> "%MONITOR_PATH%"
    echo         .container { display: flex; flex-wrap: wrap; gap: 20px; } >> "%MONITOR_PATH%"
    echo         .card { background-color: white; border-radius: 8px; padding: 15px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); flex: 1; min-width: 300px; } >> "%MONITOR_PATH%"
    echo         .card-title { font-size: 1.2em; font-weight: bold; border-bottom: 1px solid #eee; padding-bottom: 10px; margin-bottom: 15px; } >> "%MONITOR_PATH%"
    echo         .status-row { display: flex; justify-content: space-between; margin-bottom: 8px; } >> "%MONITOR_PATH%"
    echo         .value-normal { color: #2ecc71; } >> "%MONITOR_PATH%"
    echo         .value-warning { color: #f39c12; } >> "%MONITOR_PATH%"
    echo         .value-danger { color: #e74c3c; } >> "%MONITOR_PATH%"
    echo         .system-status { display: flex; align-items: center; margin-bottom: 10px; } >> "%MONITOR_PATH%"
    echo         .status-indicator { width: 15px; height: 15px; border-radius: 50%; margin-right: 10px; } >> "%MONITOR_PATH%"
    echo         .footer { margin-top: 20px; text-align: center; color: #7f8c8d; font-size: 0.8em; } >> "%MONITOR_PATH%"
    echo     </style> >> "%MONITOR_PATH%"
    echo </head> >> "%MONITOR_PATH%"
    echo <body> >> "%MONITOR_PATH%"
    echo     <div class="header"> >> "%MONITOR_PATH%"
    echo         <h1>Wastewater Treatment Plant Monitoring</h1> >> "%MONITOR_PATH%"
    echo     </div> >> "%MONITOR_PATH%"
    echo >> "%MONITOR_PATH%"
    echo     <div class="container"> >> "%MONITOR_PATH%"
    echo         <div class="card"> >> "%MONITOR_PATH%"
    echo             <div class="card-title">System Status</div> >> "%MONITOR_PATH%"
    echo             <div class="system-status"> >> "%MONITOR_PATH%"
    echo                 <div class="status-indicator" id="systemStatusIndicator"></div> >> "%MONITOR_PATH%"
    echo                 <div id="systemStatusText">Unknown</div> >> "%MONITOR_PATH%"
    echo             </div> >> "%MONITOR_PATH%"
    echo             <div class="status-row"> >> "%MONITOR_PATH%"
    echo                 <div>Auto Mode:</div> >> "%MONITOR_PATH%"
    echo                 <div id="autoMode">--</div> >> "%MONITOR_PATH%"
    echo             </div> >> "%MONITOR_PATH%"
    echo             <div class="status-row"> >> "%MONITOR_PATH%"
    echo                 <div>Maintenance Mode:</div> >> "%MONITOR_PATH%"
    echo                 <div id="maintenanceMode">--</div> >> "%MONITOR_PATH%"
    echo             </div> >> "%MONITOR_PATH%"
    echo             <div class="status-row"> >> "%MONITOR_PATH%"
    echo                 <div>Storm Mode:</div> >> "%MONITOR_PATH%"
    echo                 <div id="stormMode">--</div> >> "%MONITOR_PATH%"
    echo             </div> >> "%MONITOR_PATH%"
    echo             <div class="status-row"> >> "%MONITOR_PATH%"
    echo                 <div>Alarm Status:</div> >> "%MONITOR_PATH%"
    echo                 <div id="alarmStatus">--</div> >> "%MONITOR_PATH%"
    echo             </div> >> "%MONITOR_PATH%"
    echo         </div> >> "%MONITOR_PATH%"
    echo >> "%MONITOR_PATH%"
    echo         <div class="card"> >> "%MONITOR_PATH%"
    echo             <div class="card-title">Key Process Variables</div> >> "%MONITOR_PATH%"
    echo             <div class="status-row"> >> "%MONITOR_PATH%"
    echo                 <div>Flow Rate:</div> >> "%MONITOR_PATH%"
    echo                 <div id="flowRate">-- m³/hr</div> >> "%MONITOR_PATH%"
    echo             </div> >> "%MONITOR_PATH%"
    echo             <div class="status-row"> >> "%MONITOR_PATH%"
    echo                 <div>pH Value:</div> >> "%MONITOR_PATH%"
    echo                 <div id="phValue">--</div> >> "%MONITOR_PATH%"
    echo             </div> >> "%MONITOR_PATH%"
    echo             <div class="status-row"> >> "%MONITOR_PATH%"
    echo                 <div>Dissolved Oxygen:</div> >> "%MONITOR_PATH%"
    echo                 <div id="dissolvedOxygen">-- mg/L</div> >> "%MONITOR_PATH%"
    echo             </div> >> "%MONITOR_PATH%"
    echo             <div class="status-row"> >> "%MONITOR_PATH%"
    echo                 <div>Turbidity:</div> >> "%MONITOR_PATH%"
    echo                 <div id="turbidity">-- NTU</div> >> "%MONITOR_PATH%"
    echo             </div> >> "%MONITOR_PATH%"
    echo             <div class="status-row"> >> "%MONITOR_PATH%"
    echo                 <div>Chlorine:</div> >> "%MONITOR_PATH%"
    echo                 <div id="chlorine">-- mg/L</div> >> "%MONITOR_PATH%"
    echo             </div> >> "%MONITOR_PATH%"
    echo         </div> >> "%MONITOR_PATH%"
    echo >> "%MONITOR_PATH%"
    echo         <div class="card"> >> "%MONITOR_PATH%"
    echo             <div class="card-title">Tank Levels</div> >> "%MONITOR_PATH%"
    echo             <div class="status-row"> >> "%MONITOR_PATH%"
    echo                 <div>Primary Tank:</div> >> "%MONITOR_PATH%"
    echo                 <div id="tankLevel1">-- m</div> >> "%MONITOR_PATH%"
    echo             </div> >> "%MONITOR_PATH%"
    echo             <div class="status-row"> >> "%MONITOR_PATH%"
    echo                 <div>Secondary Tank:</div> >> "%MONITOR_PATH%"
    echo                 <div id="tankLevel2">-- m</div> >> "%MONITOR_PATH%"
    echo             </div> >> "%MONITOR_PATH%"
    echo         </div> >> "%MONITOR_PATH%"
    echo >> "%MONITOR_PATH%"
    echo         <div class="card"> >> "%MONITOR_PATH%"
    echo             <div class="card-title">Equipment Status</div> >> "%MONITOR_PATH%"
    echo             <div class="status-row"> >> "%MONITOR_PATH%"
    echo                 <div>Intake Pump (P101):</div> >> "%MONITOR_PATH%"
    echo                 <div id="pumpP101">--</div> >> "%MONITOR_PATH%"
    echo             </div> >> "%MONITOR_PATH%"
    echo             <div class="status-row"> >> "%MONITOR_PATH%"
    echo                 <div>Transfer Pump (P102):</div> >> "%MONITOR_PATH%"
    echo                 <div id="pumpP102">--</div> >> "%MONITOR_PATH%"
    echo             </div> >> "%MONITOR_PATH%"
    echo             <div class="status-row"> >> "%MONITOR_PATH%"
    echo                 <div>Primary Mixer (M101):</div> >> "%MONITOR_PATH%"
    echo                 <div id="mixerM101">--</div> >> "%MONITOR_PATH%"
    echo             </div> >> "%MONITOR_PATH%"
    echo             <div class="status-row"> >> "%MONITOR_PATH%"
    echo                 <div>Secondary Mixer (M102):</div> >> "%MONITOR_PATH%"
    echo                 <div id="mixerM102">--</div> >> "%MONITOR_PATH%"
    echo             </div> >> "%MONITOR_PATH%"
    echo             <div class="status-row"> >> "%MONITOR_PATH%"
    echo                 <div>Aeration Blower:</div> >> "%MONITOR_PATH%"
    echo                 <div id="blower">--</div> >> "%MONITOR_PATH%"
    echo             </div> >> "%MONITOR_PATH%"
    echo             <div class="status-row"> >> "%MONITOR_PATH%"
    echo                 <div>UV System:</div> >> "%MONITOR_PATH%"
    echo                 <div id="uvSystem">--</div> >> "%MONITOR_PATH%"
    echo             </div> >> "%MONITOR_PATH%"
    echo         </div> >> "%MONITOR_PATH%"
    echo >> "%MONITOR_PATH%"
    echo         <div class="card"> >> "%MONITOR_PATH%"
    echo             <div class="card-title">Performance Metrics</div> >> "%MONITOR_PATH%"
    echo             <div class="status-row"> >> "%MONITOR_PATH%"
    echo                 <div>Treatment Efficiency:</div> >> "%MONITOR_PATH%"
    echo                 <div id="treatmentEfficiency">-- %</div> >> "%MONITOR_PATH%"
    echo             </div> >> "%MONITOR_PATH%"
    echo             <div class="status-row"> >> "%MONITOR_PATH%"
    echo                 <div>Energy Consumption:</div> >> "%MONITOR_PATH%"
    echo                 <div id="energyConsumption">-- kW</div> >> "%MONITOR_PATH%"
    echo             </div> >> "%MONITOR_PATH%"
    echo             <div class="status-row"> >> "%MONITOR_PATH%"
    echo                 <div>Total Flow Today:</div> >> "%MONITOR_PATH%"
    echo                 <div id="totalFlowToday">-- m³</div> >> "%MONITOR_PATH%"
    echo             </div> >> "%MONITOR_PATH%"
    echo             <div class="status-row"> >> "%MONITOR_PATH%"
    echo                 <div>Chemical Usage:</div> >> "%MONITOR_PATH%"
    echo                 <div id="chemicalUsage">-- L</div> >> "%MONITOR_PATH%"
    echo             </div> >> "%MONITOR_PATH%"
    echo         </div> >> "%MONITOR_PATH%"
    echo     </div> >> "%MONITOR_PATH%"
    echo >> "%MONITOR_PATH%"
    echo     <div class="footer"> >> "%MONITOR_PATH%"
    echo         <p>Last Updated: <span id="lastUpdated">--</span></p> >> "%MONITOR_PATH%"
    echo         <p>Wastewater Treatment Plant Monitoring System | Version 1.0</p> >> "%MONITOR_PATH%"
    echo     </div> >> "%MONITOR_PATH%"
    echo >> "%MONITOR_PATH%"
    echo     <script> >> "%MONITOR_PATH%"
    echo         function updateData() { >> "%MONITOR_PATH%"
    echo             fetch('/api/data') >> "%MONITOR_PATH%"
    echo                 .then(response => response.json()) >> "%MONITOR_PATH%"
    echo                 .then(data => { >> "%MONITOR_PATH%"
    echo                     // Update system status >> "%MONITOR_PATH%"
    echo                     const statusIndicator = document.getElementById('systemStatusIndicator'); >> "%MONITOR_PATH%"
    echo                     const statusText = document.getElementById('systemStatusText'); >> "%MONITOR_PATH%"
    echo >> "%MONITOR_PATH%"
    echo                     if (data.emergency_stop) { >> "%MONITOR_PATH%"
    echo                         statusIndicator.style.backgroundColor = '#e74c3c'; // Red >> "%MONITOR_PATH%"
    echo                         statusText.textContent = 'EMERGENCY STOP'; >> "%MONITOR_PATH%"
    echo                     } else if (!data.system_running) { >> "%MONITOR_PATH%"
    echo                         statusIndicator.style.backgroundColor = '#f39c12'; // Yellow >> "%MONITOR_PATH%"
    echo                         statusText.textContent = 'STOPPED'; >> "%MONITOR_PATH%"
    echo                     } else if (data.alarm_active) { >> "%MONITOR_PATH%"
    echo                         statusIndicator.style.backgroundColor = '#e67e22'; // Orange >> "%MONITOR_PATH%"
    echo                         statusText.textContent = 'RUNNING (ALARM)'; >> "%MONITOR_PATH%"
    echo                     } else { >> "%MONITOR_PATH%"
    echo                         statusIndicator.style.backgroundColor = '#2ecc71'; // Green >> "%MONITOR_PATH%"
    echo                         statusText.textContent = 'RUNNING'; >> "%MONITOR_PATH%"
    echo                     } >> "%MONITOR_PATH%"
    echo >> "%MONITOR_PATH%"
    echo                     // Update mode status >> "%MONITOR_PATH%"
    echo                     document.getElementById('autoMode').textContent = data.auto_mode ? 'ON' : 'OFF'; >> "%MONITOR_PATH%"
    echo                     document.getElementById('maintenanceMode').textContent = data.maintenance_mode ? 'ON' : 'OFF'; >> "%MONITOR_PATH%"
    echo                     document.getElementById('stormMode').textContent = data.storm_mode ? 'ON' : 'OFF'; >> "%MONITOR_PATH%"
    echo                     document.getElementById('alarmStatus').textContent = data.alarm_active ? 'ACTIVE' : 'NORMAL'; >> "%MONITOR_PATH%"
    echo                     document.getElementById('alarmStatus').className = data.alarm_active ? 'value-danger' : 'value-normal'; >> "%MONITOR_PATH%"
    echo >> "%MONITOR_PATH%"
    echo                     // Update process variables >> "%MONITOR_PATH%"
    echo                     document.getElementById('flowRate').textContent = data.flow_rate.toFixed(1) + ' m³/hr'; >> "%MONITOR_PATH%"
    echo                     >> "%MONITOR_PATH%"
    echo                     const phValue = document.getElementById('phValue'); >> "%MONITOR_PATH%"
    echo                     phValue.textContent = data.ph_value.toFixed(2); >> "%MONITOR_PATH%"
    echo                     if (data.ph_value < 6.5 || data.ph_value > 8.5) { >> "%MONITOR_PATH%"
    echo                         phValue.className = 'value-danger'; >> "%MONITOR_PATH%"
    echo                     } else if (data.ph_value < 7.0 || data.ph_value > 8.0) { >> "%MONITOR_PATH%"
    echo                         phValue.className = 'value-warning'; >> "%MONITOR_PATH%"
    echo                     } else { >> "%MONITOR_PATH%"
    echo                         phValue.className = 'value-normal'; >> "%MONITOR_PATH%"
    echo                     } >> "%MONITOR_PATH%"
    echo >> "%MONITOR_PATH%"
    echo                     document.getElementById('dissolvedOxygen').textContent = data.dissolved_oxygen.toFixed(2) + ' mg/L'; >> "%MONITOR_PATH%"
    echo                     >> "%MONITOR_PATH%"
    echo                     const turbidity = document.getElementById('turbidity'); >> "%MONITOR_PATH%"
    echo                     turbidity.textContent = data.turbidity.toFixed(1) + ' NTU'; >> "%MONITOR_PATH%"
    echo                     if (data.turbidity > 70) { >> "%MONITOR_PATH%"
    echo                         turbidity.className = 'value-danger'; >> "%MONITOR_PATH%"
    echo                     } else if (data.turbidity > 50) { >> "%MONITOR_PATH%"
    echo                         turbidity.className = 'value-warning'; >> "%MONITOR_PATH%"
    echo                     } else { >> "%MONITOR_PATH%"
    echo                         turbidity.className = 'value-normal'; >> "%MONITOR_PATH%"
    echo                     } >> "%MONITOR_PATH%"
    echo >> "%MONITOR_PATH%"
    echo                     document.getElementById('chlorine').textContent = data.chlorine.toFixed(2) + ' mg/L'; >> "%MONITOR_PATH%"
    echo >> "%MONITOR_PATH%"
    echo                     // Update tank levels >> "%MONITOR_PATH%"
    echo                     document.getElementById('tankLevel1').textContent = data.tank_level_1.toFixed(2) + ' m'; >> "%MONITOR_PATH%"
    echo                     document.getElementById('tankLevel2').textContent = data.tank_level_2.toFixed(2) + ' m'; >> "%MONITOR_PATH%"
    echo >> "%MONITOR_PATH%"
    echo                     // Update equipment status >> "%MONITOR_PATH%"
    echo                     document.getElementById('pumpP101').textContent = data.pump_p101_status ? 'RUNNING' : 'STOPPED'; >> "%MONITOR_PATH%"
    echo                     document.getElementById('pumpP101').className = data.pump_p101_status ? 'value-normal' : ''; >> "%MONITOR_PATH%"
    echo                     >> "%MONITOR_PATH%"
    echo                     document.getElementById('pumpP102').textContent = data.pump_p102_status ? 'RUNNING' : 'STOPPED'; >> "%MONITOR_PATH%"
    echo                     document.getElementById('pumpP102').className = data.pump_p102_status ? 'value-normal' : ''; >> "%MONITOR_PATH%"
    echo                     >> "%MONITOR_PATH%"
    echo                     document.getElementById('mixerM101').textContent = data.mixer_m101_status ? 'RUNNING' : 'STOPPED'; >> "%MONITOR_PATH%"
    echo                     document.getElementById('mixerM101').className = data.mixer_m101_status ? 'value-normal' : ''; >> "%MONITOR_PATH%"
    echo                     >> "%MONITOR_PATH%"
    echo                     document.getElementById('mixerM102').textContent = data.mixer_m102_status ? 'RUNNING' : 'STOPPED'; >> "%MONITOR_PATH%"
    echo                     document.getElementById('mixerM102').className = data.mixer_m102_status ? 'value-normal' : ''; >> "%MONITOR_PATH%"
    echo                     >> "%MONITOR_PATH%"
    echo                     document.getElementById('blower').textContent = data.blower_status ? 'RUNNING' : 'STOPPED'; >> "%MONITOR_PATH%"
    echo                     document.getElementById('blower').className = data.blower_status ? 'value-normal' : ''; >> "%MONITOR_PATH%"
    echo                     >> "%MONITOR_PATH%"
    echo                     document.getElementById('uvSystem').textContent = data.uv_system_status ? 'RUNNING' : 'STOPPED'; >> "%MONITOR_PATH%"
    echo                     document.getElementById('uvSystem').className = data.uv_system_status ? 'value-normal' : ''; >> "%MONITOR_PATH%"
    echo >> "%MONITOR_PATH%"
    echo                     // Update performance metrics >> "%MONITOR_PATH%"
    echo                     document.getElementById('treatmentEfficiency').textContent = data.treatment_efficiency.toFixed(1) + ' %'; >> "%MONITOR_PATH%"
    echo                     document.getElementById('energyConsumption').textContent = data.energy_consumption.toFixed(1) + ' kW'; >> "%MONITOR_PATH%"
    echo                     document.getElementById('totalFlowToday').textContent = data.total_flow_today.toFixed(1) + ' m³'; >> "%MONITOR_PATH%"
    echo                     document.getElementById('chemicalUsage').textContent = data.chemical_usage.toFixed(1) + ' L'; >> "%MONITOR_PATH%"
    echo >> "%MONITOR_PATH%"
    echo                     // Update timestamp >> "%MONITOR_PATH%"
    echo                     document.getElementById('lastUpdated').textContent = new Date().toLocaleTimeString(); >> "%MONITOR_PATH%"
    echo                 }) >> "%MONITOR_PATH%"
    echo                 .catch(error => { >> "%MONITOR_PATH%"
    echo                     console.error('Error fetching data:', error); >> "%MONITOR_PATH%"
    echo                 }); >> "%MONITOR_PATH%"
    echo         } >> "%MONITOR_PATH%"
    echo >> "%MONITOR_PATH%"
    echo         // Update data every 2 seconds >> "%MONITOR_PATH%"
    echo         setInterval(updateData, 2000); >> "%MONITOR_PATH%"
    echo >> "%MONITOR_PATH%"
    echo         // Initial update >> "%MONITOR_PATH%"
    echo         updateData(); >> "%MONITOR_PATH%"
    echo     </script> >> "%MONITOR_PATH%"
    echo </body> >> "%MONITOR_PATH%"
    echo </html> >> "%MONITOR_PATH%"
    echo """ >> "%MONITOR_PATH%"
    echo. >> "%MONITOR_PATH%"
    echo if __name__ == "__main__": >> "%MONITOR_PATH%"
    echo     try: >> "%MONITOR_PATH%"
    echo         try: >> "%MONITOR_PATH%"
    echo             import flask >> "%MONITOR_PATH%"
    echo         except ImportError: >> "%MONITOR_PATH%"
    echo             print("Flask not installed. Installing...") >> "%MONITOR_PATH%"
    echo             import subprocess >> "%MONITOR_PATH%"
    echo             subprocess.check_call([sys.executable, "-m", "pip", "install", "flask"]) >> "%MONITOR_PATH%"
    echo             import flask >> "%MONITOR_PATH%"
    echo. >> "%MONITOR_PATH%"
    echo         monitoring_system = WastewaterMonitoringSystem() >> "%MONITOR_PATH%"
    echo     except KeyboardInterrupt: >> "%MONITOR_PATH%"
    echo         print("\nMonitoring system shutting down...") >> "%MONITOR_PATH%"
    echo     except Exception as e: >> "%MONITOR_PATH%"
    echo         print(f"Error: {e}") >> "%MONITOR_PATH%"
)

:: Run the monitoring system
cd %BASE_PATH%
echo Launching system monitoring...
%PYTHON_PATH% %MONITOR_PATH%

exit /b 0
